### ISSUE TITLE
Sachin: Agile Development: 4 Weeks

### ISSUE THREAD

**Issue by sachinpalaye** [HYF-Class20/agile-devolopment-group4-all-about-trees#18]
## [0. Developing HTML & CSS](./0-developing-html-and-css)

Practice with the skills, tools, and workflows you will need to efficiently
develop websites written with HTML & CSS.

- 🥚 **VSCode**: you can ...
  - [ ] use the _LiveServer extension_ to launch an HTML page in the browser
  - [ ] use autocomplete to begin a new HTML document, create new tags, and much
        more
  - [ ] use the _HTML CSS Support_ and _IntelliSense fo CSS class names_
        extensions to make writing HTML & CSS more efficient
- 🥚 **Formatting HTML & CSS**: You can ...
  - [ ] use VSCode configurations to format your code on save
  - [ ] use `npm run format` to format all the code in your repository
- [ ] 🥚 **Linting CSS**: You can use the `npm run lint:css` script to find
      mistakes in your CSS, and you can fix the mistakes.
- [ ] 🥚 **Validating HTML**: You can use the `npm run validate:html` script to
      find mistakes in your CSS, and you can fix the mistakes.
- 🥚 **Browser Developer Tools**: You can ...
  - [ ] inspect the source code of a web page using the Sources tab
  - [ ] find any part of the web page in the Elements tab of your Dev Tools DOM
        inspector
  - [ ] find the styles for any element in the Elements tab
  - [ ] make temporary changes in a web page from the Elements tab to see how
        they will look

**Comment by HerbertHomolka1** [comment]
The check in shouldn't be here.
Post it here instead: https://github.com/HYF-Class20/home/issues
